sudo: required
services:
  - docker

before_install: 
  - docker build -t geminiabhijeet/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true geminiabhijeet/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  evn: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-223637281421"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
